apps/home/urls.py
# coding=utf-8
from django.conf.urls import url

from apps.home.views import HomeView, CreateSimpleObjectView, UpdateSimpleObjectView

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='index'),
    url(r'^create/$', CreateSimpleObjectView.as_view(), name='create'),
    url(r'^update/(?P<pk>\d+)/$', UpdateSimpleObjectView.as_view(), name='update'),
]

project/urls.py
# coding=utf-8
"""project URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.home.urls', namespace='home')),
    url(r'^admin/', admin.site.urls),
]

apps/home/models.py
# coding=utf-8
from django.db import models


class SimpleObject(models.Model):
    """Simple object to test a CRU flow"""
    some_string = models.CharField(max_length=250)
    some_text = models.TextField()
    some_integer_number = models.IntegerField()

    def __str__(self):
        return "{id}: {string}. {text}, {number}".format(
            id=self.id, string=self.some_string, text=self.some_text,
            number=self.some_integer_number)

apps/home/forms.py
# coding=utf-8
from django import forms

from apps.home.models import SimpleObject


class SimpleObjectForm(forms.ModelForm):
    class Meta:
        model = SimpleObject
        fields = ['some_string', 'some_text', 'some_integer_number']

apps/home/views.py
# coding=utf-8
from django.urls.base import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.list import ListView

from apps.home.forms import SimpleObjectForm
from apps.home.models import SimpleObject


class HomeView(ListView):
    model = SimpleObject
    template_name = 'index.html'


class CreateSimpleObjectView(CreateView):
    form_class = SimpleObjectForm
    template_name = 'add_edit.html'
    success_url = reverse_lazy('home:index')


class UpdateSimpleObjectView(UpdateView):
    model = SimpleObject
    form_class = SimpleObjectForm
    template_name = 'add_edit.html'
    success_url = reverse_lazy('home:index')

apps/home/templates/add_edit.html
{% extends 'base.html' %}

{% block container %}
  <h2>Add some new object</h2>
  <form action="." method="post">
    {% csrf_token %}
    <table class="table table-striped">
      {{ form.as_table }}
    </table>
    <button class="btn btn-success">Add new object</button>
  </form>
{% endblock %}

apps/home/templates/index.html
{% extends 'base.html' %}
{% block container %}
  <div class="row">
    <div class="col-md-12">
      <h1>Welcome to this simple project</h1>
      <h3>Here is a list of simple objects:</h3>
    </div>
  </div>
  <div class="row">
    <div class="col-md-8">
      <ul>
        {% for simpleobject in simpleobject_list %}
          <li>
            <a href="{% url 'home:update' pk=simpleobject.pk %}">{{ simpleobject }}</a>
          </li>
        {% endfor %}
      </ul>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <div class="text-center">
        <a href="{% url 'home:create' %}" class="btn btn-primary">Create new object</a>
      </div>
    </div>
  </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
        integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
<div class="container">
  {% block container %}{% endblock %}
</div>
</body>
</html>